// Mirrors pulseguard-ai's sibling schemas/signal.py SignalCategory enum —
// kept as a flat list here (not generated) since it's fixed taxonomy, not
// runtime data.
export const ALL_CATEGORIES = [
  'telecom_mobile',
  'telecom_broadband',
  'telecom_bundled',
  'telecom_porting',
  'telecom_billing',
  'fintech_credit_card',
  'fintech_personal_loan',
  'fintech_bnpl',
  'fintech_banking',
  'fintech_insurance',
  'fintech_investment',
  'home_internet',
  'home_security',
  'home_utilities',
  'home_moving',
  'home_repair',
  'dtc_subscription',
  'dtc_health',
  'dtc_beauty',
  'dtc_food',
  'dtc_fitness',
  'saas_crm',
  'saas_productivity',
  'saas_security',
  'saas_hr',
  'saas_marketing',
  'health_insurance',
  'health_pharmacy',
  'health_telemedicine',
  'auto_insurance',
  'auto_finance',
  'auto_ev',
  'travel_airline',
  'travel_hotel',
  'travel_booking',
  'edu_online_learning',
  'edu_test_prep',
  'energy_solar',
  'energy_utility',
  'realestate_rental',
  'realestate_mortgage',
] as const;

export type CategoryValue = (typeof ALL_CATEGORIES)[number];
